[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH",
    "apt-get install --assume-yes --no-install-recommends libclang-10-dev clang-10",
]
