[upstream]
peer_address = "relays-new.cardano-mainnet.iohk.io:3001"
network_magic = 764824073
is_testnet = false

[storage]
path = "./data"
wal_size = 1000

[sync]
pull_batch_size = 200

[submit]
prune_height = 10000

[genesis]
byron_path = "./byron.json"
shelley_path = "./shelley.json"
alonzo_path = "./alonzo.json"

[serve.grpc]
listen_address = "[::]:50051"

[serve.ouroboros]
listen_address = "[::]:30013"
magic = 764824073

[logging]
max_level = "debug"
