[upstream]
peer_address = "relays-new.cardano-mainnet.iohk.io:3001"
network_magic = 764824073

[rolldb]
path = "./tmp/rolldb"
k_param = 1000

[applydb]
path = "./tmp/applydb"

[serve.grpc]
listen_address = "[::]:50051"

[serve.ouroboros]
listen_address = "localhost:30013"
magic = 0

[byron]
path = "./byron.json"
hash = "xxx"
