#![allow(dead_code)]

use std::net::TcpStream;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicU16, Ordering};
use std::time::{Duration, Instant};

use tempfile::TempDir;

pub struct Scenario {
    pub name: &'static str,
    pub port_prefix: u16,
    pub expect_ports: bool,
}

pub const SCENARIOS: &[Scenario] = &[
    Scenario {
        name: "preview-full-explicit",
        port_prefix: 6540,
        expect_ports: true,
    },
    Scenario {
        name: "preview-full-implicit",
        port_prefix: 6550,
        expect_ports: true,
    },
    Scenario {
        name: "preview-min-implicit",
        port_prefix: 6560,
        expect_ports: false,
    },
    Scenario {
        name: "mainnet-full-implicit",
        port_prefix: 6570,
        expect_ports: true,
    },
    Scenario {
        name: "preprod-full-implicit",
        port_prefix: 6580,
        expect_ports: true,
    },
    Scenario {
        name: "custom-network",
        port_prefix: 6590,
        expect_ports: true,
    },
];

/// Where a scenario's checked-in fixture lives.
///
/// `dolos.toml` is the only tracked file in each of these directories. Genesis
/// files, `data/`, `blocks/` and the rest are generated by the run — which is
/// what makes seeding a workspace from one a copy of a single file.
fn fixture_path(scenario: &Scenario) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/e2e/scenarios")
        .join(scenario.name)
}

/// Ports handed out to workspaces, one block of ten each.
///
/// Deliberately above every `Scenario::port_prefix` (6540..6599), which buys
/// two things: a workspace can never collide with a daemon a previous run left
/// holding a fixture's ports, and the rewrite in `rewrite_ports` can never
/// rewrite a port it has itself just written.
const WORKSPACE_PORT_BASE: u16 = 7100;
const WORKSPACE_PORT_STRIDE: u16 = 10;

static NEXT_PORT_PREFIX: AtomicU16 = AtomicU16::new(WORKSPACE_PORT_BASE);

/// An isolated working directory for a single test.
///
/// The directories under `tests/e2e/scenarios/` are fixtures, not working
/// directories: a run writes its genesis files, `data/`, `blocks/` and unix
/// socket right beside the `dolos.toml` it read. Two tests sharing a fixture
/// therefore put two nodes in one directory, and the second one to open the
/// state store dies on `FjallError: Locked` — which is what
/// `snapshot_roundtrip_for_preview_full_explicit` and
/// `stele_roundtrip_for_preview_full_explicit` did to each other once both
/// existed, since libtest runs the tests in a binary in parallel.
///
/// A workspace is that fixture copied per test: its own `dolos.toml` under
/// `CARGO_TARGET_TMPDIR`, and its own block of ports, so the suite stays
/// parallel and adding a second test to a scenario stays safe.
pub struct ScenarioWorkspace {
    name: &'static str,
    expect_ports: bool,
    port_prefix: u16,
    dir: TempDir,
}

impl ScenarioWorkspace {
    pub fn new(scenario: &Scenario) -> Self {
        let port_prefix = NEXT_PORT_PREFIX.fetch_add(WORKSPACE_PORT_STRIDE, Ordering::Relaxed);

        let dir =
            TempDir::with_prefix_in(format!("{}-", scenario.name), env!("CARGO_TARGET_TMPDIR"))
                .expect("failed to create scenario workspace");

        let fixture = fixture_path(scenario).join("dolos.toml");

        let config = std::fs::read_to_string(&fixture)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", fixture.display()));

        let rewritten = rewrite_ports(&config, scenario.port_prefix, port_prefix);

        assert!(
            !scenario.expect_ports || rewritten != config,
            "scenario {} is declared to serve ports at {} but its dolos.toml names none",
            scenario.name,
            scenario.port_prefix,
        );

        std::fs::write(dir.path().join("dolos.toml"), rewritten)
            .expect("failed to write workspace config");

        Self {
            name: scenario.name,
            expect_ports: scenario.expect_ports,
            port_prefix,
            dir,
        }
    }

    pub fn path(&self) -> &Path {
        self.dir.path()
    }

    pub fn name(&self) -> &'static str {
        self.name
    }

    pub fn expect_ports(&self) -> bool {
        self.expect_ports
    }

    pub fn port(&self, suffix: u16) -> u16 {
        self.port_prefix + suffix
    }
}

/// Move every port in a scenario config from one block of ten to another.
///
/// A substring rewrite rather than a TOML round trip, so a workspace's config
/// differs from its fixture in the ports and in nothing else. Correct only
/// because the two blocks never overlap — see `WORKSPACE_PORT_BASE`.
fn rewrite_ports(config: &str, from_prefix: u16, to_prefix: u16) -> String {
    debug_assert!(
        to_prefix >= from_prefix + WORKSPACE_PORT_STRIDE
            || from_prefix >= to_prefix + WORKSPACE_PORT_STRIDE,
        "port blocks {from_prefix} and {to_prefix} overlap"
    );

    (0..WORKSPACE_PORT_STRIDE).fold(config.to_string(), |acc, suffix| {
        acc.replace(
            &format!(":{}", from_prefix + suffix),
            &format!(":{}", to_prefix + suffix),
        )
    })
}

pub fn prepare_scenario_process(workspace: &ScenarioWorkspace) -> Command {
    let dolos_bin = env!("CARGO_BIN_EXE_dolos");

    let mut cmd = Command::new(dolos_bin);
    cmd.current_dir(workspace.path());
    cmd
}

pub fn wait_for_tcp_port(workspace: &ScenarioWorkspace, port_suffix: u16, timeout: Duration) {
    let port = workspace.port(port_suffix);

    let start = Instant::now();
    let mut connected = false;

    while start.elapsed() < timeout {
        if TcpStream::connect(format!("127.0.0.1:{port}")).is_ok() {
            connected = true;
            break;
        }
        std::thread::sleep(Duration::from_millis(100));
    }

    if !connected {
        panic!("timed out waiting for port {port} to open");
    }
}

pub fn wait_for_socket_file(workspace: &ScenarioWorkspace, relative_path: &str, timeout: Duration) {
    let path = workspace.path().join(relative_path);

    let start = Instant::now();
    let mut found = false;

    while start.elapsed() < timeout {
        if std::fs::metadata(&path).is_ok() {
            found = true;
            break;
        }
        std::thread::sleep(Duration::from_millis(100));
    }

    if !found {
        panic!(
            "timed out waiting for file {} to appear",
            path.to_string_lossy()
        );
    }
}

pub fn assert_port_released(workspace: &ScenarioWorkspace, port_suffix: u16) {
    let port = workspace.port(port_suffix);
    assert!(TcpStream::connect(format!("127.0.0.1:{port}")).is_err());
}

pub fn assert_file_released(workspace: &ScenarioWorkspace, relative_path: &str) {
    let path = workspace.path().join(relative_path);
    assert!(std::fs::metadata(path).is_err());
}

pub fn shutdown_gracefully(handle: &mut Child) {
    nix::sys::signal::kill(
        nix::unistd::Pid::from_raw(handle.id() as i32),
        nix::sys::signal::Signal::SIGTERM,
    )
    .expect("failed to kill process");

    handle.wait().expect("failed to wait for process");
}

pub fn reset_and_bootstrap(workspace: &ScenarioWorkspace) {
    let mut cmd = prepare_scenario_process(workspace);

    let reset = cmd
        .args(["doctor", "reset-genesis"])
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .output()
        .expect("failed to reset genesis");

    assert!(
        reset.status.success(),
        "doctor reset-genesis failed for scenario {}: {}",
        workspace.name(),
        String::from_utf8_lossy(&reset.stderr)
    );

    let mut cmd = prepare_scenario_process(workspace);

    let bootstrap = cmd
        .args(["bootstrap", "relay", "--force"])
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .output()
        .expect("failed to bootstrap data");

    assert!(
        bootstrap.status.success(),
        "bootstrap relay failed for scenario {}: {}",
        workspace.name(),
        String::from_utf8_lossy(&bootstrap.stderr)
    );
}

pub fn fetch_summary(workspace: &ScenarioWorkspace) -> dolos::cli::DataSummary {
    let mut cmd = prepare_scenario_process(workspace);

    let data = cmd
        .args(["data", "summary"])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .expect("failed to get data summary");

    assert!(
        data.status.success(),
        "data summary failed for scenario {}: {}",
        workspace.name(),
        String::from_utf8_lossy(&data.stderr)
    );

    serde_json::from_slice::<dolos::cli::DataSummary>(&data.stdout)
        .expect("failed to parse data summary")
}

pub struct ProcessGuard(Option<Child>);

impl ProcessGuard {
    pub fn new(child: Child) -> Self {
        Self(Some(child))
    }
}

impl std::ops::Deref for ProcessGuard {
    type Target = Child;

    fn deref(&self) -> &Self::Target {
        self.0.as_ref().unwrap()
    }
}

impl std::ops::DerefMut for ProcessGuard {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.0.as_mut().unwrap()
    }
}

impl Drop for ProcessGuard {
    fn drop(&mut self) {
        if let Some(mut child) = self.0.take() {
            let pid = nix::unistd::Pid::from_raw(child.id() as i32);

            if let Err(err) = nix::sys::signal::kill(pid, nix::sys::signal::Signal::SIGTERM) {
                if err == nix::Error::ESRCH {
                    return;
                }

                eprintln!("could not SIGTERM process {pid}: {err}");
            }

            if let Err(err) = child.wait() {
                eprintln!("error waiting for process {pid} to exit: {err}");
            }
        }
    }
}
