[package]
name = "dolos-fjall"
version.workspace = true
edition.workspace = true

[dependencies]
dolos-core = { path = "../core" }
dolos-redb3 = { path = "../redb3" }
fjall = "3.1.0"
tracing.workspace = true
thiserror.workspace = true
bincode.workspace = true
xxhash-rust.workspace = true
pallas.workspace = true
tempfile = "3"

[dev-dependencies]
dolos-testing = { path = "../testing" }
