[upstream]
block_production_interval = 10

[storage]
version = "v3"
path = "data"

[genesis]
byron_path = "byron.json"
shelley_path = "shelley.json"
alonzo_path = "alonzo.json"
conway_path = "conway.json"
force_protocol = 6

[sync]
max_rollback = 10000

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"

[serve.ouroboros]
listen_path = "dolos.socket"

[serve.trp]
listen_address = "[::]:8000"

[chain]
type = "cardano"
magic = 2
is_testnet = true

[telemetry]
enabled = true

[logging]
max_level = "DEBUG"
